version: "3.1"

services:
  mysql:
    build: .
    image: mysql:8.0
    restart: always
    container_name: project_manager_db
    env_file:
      - docker.properties
    ports:
      - "3307:3306"
    volumes:
      - project-manager-data:/var/lib/mysql

volumes:
  project-manager-data:
